### PR TITLE
autogenerated GUI and visualizer

### PR DESCRIPTION
**Pull request by essteban**

### CODE REVIEW

**Comment by cchafe** [comment]
hey -- thanks! -- I need a hint on how to check out this PR, I tried
`git checkout essteban:webchuck-ide`
and got
`error: pathspec 'essteban:webchuck-ide' did not match any file(s) known to git`

**Comment by essteban** [comment]
I think it's because my fork hasn't been merged so, someone could merge it to ccrma/webchuck-ide branch or you could download my fork and checkout to webchuck-ide branch.

**Comment by terryzfeng** [comment]
@essteban I added a couple of changes on my branch so now we always cache the code (saved across browser sessions). Hopefully, that shouldn't change anything on your side so let me know if everything works!

**Comment by gewang** [comment]
@terryzfeng @essteban pull requests #1 and #2 have been merged into webchuck main branch @cchafe should be able to get the latest by cloning/pulling ccrma/webchuck.git; rock on!

**Pull request merged**
